CREATE TABLE IF NOT EXISTS "DIME_CAUSA_CID" (
	"SK Causa" INTEGER NOT NULL,
	"CD Causa" VARCHAR NOT NULL UNIQUE,
	"DS Causa" VARCHAR NOT NULL,
	PRIMARY KEY("SK Causa"),
	FOREIGN KEY ("SK Causa") REFERENCES "FATO_OBITO"("SK Causa CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_OBITO_PUERPERIO" (
	"SK Obito Puerperio" INTEGER NOT NULL,
	"CD Obito Puerperio" INTEGER NOT NULL UNIQUE,
	"DS Obito Puerperio" VARCHAR NOT NULL,
	PRIMARY KEY("SK Obito Puerperio"),
	FOREIGN KEY ("SK Obito Puerperio") REFERENCES "FATO_OBITO"("SK Obito Puerperio")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_MORTE_OCORREU" (
	"SK Morte Ocorreu" INTEGER NOT NULL,
	"CD Morte Ocorreu" INTEGER NOT NULL UNIQUE,
	"DS Morte Ocorreu" VARCHAR NOT NULL,
	PRIMARY KEY("SK Morte Ocorreu"),
	FOREIGN KEY ("SK Morte Ocorreu") REFERENCES "FATO_OBITO"("SK Morte Ocorreu")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_METODO_PARTO" (
	"SK Tipo Parto" INTEGER NOT NULL,
	"CD Tipo Parto" INTEGER NOT NULL UNIQUE,
	"DS Parto" VARCHAR NOT NULL,
	PRIMARY KEY("SK Tipo Parto"),
	FOREIGN KEY ("SK Tipo Parto") REFERENCES "FATO_OBITO"("SK Metodo Parto")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_GESTACAO_MULTIPLA" (
	"SK Tipo Gravidez" INTEGER NOT NULL,
	"CD Tipo Gravidez" INTEGER NOT NULL UNIQUE,
	"DS Gravidez" VARCHAR NOT NULL UNIQUE,
	PRIMARY KEY("SK Tipo Gravidez"),
	FOREIGN KEY ("SK Tipo Gravidez") REFERENCES "FATO_OBITO"("SK Gestacao Multipla")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_ESCOLARIDADE" (
	"SK Escolaridade" INTEGER NOT NULL,
	"CD Escolaridade" INTEGER NOT NULL UNIQUE,
	"DS Escolaridade" VARCHAR NOT NULL,
	PRIMARY KEY("SK Escolaridade"),
	FOREIGN KEY ("SK Escolaridade") REFERENCES "FATO_OBITO"("SK Escolaridade Mae")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_LOCAL_OCORRENCIA" (
	"SK Local Ocorrencia" INTEGER NOT NULL,
	"CD Ocorrencia" INTEGER NOT NULL UNIQUE,
	"DS Local Ocorrencia" VARCHAR NOT NULL,
	PRIMARY KEY("SK Local Ocorrencia"),
	FOREIGN KEY ("SK Local Ocorrencia") REFERENCES "FATO_OBITO"("SK Local Ocorrencia")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_TEMPO" (
	"SK Tempo" INTEGER NOT NULL UNIQUE,
	"CD Tempo" INTEGER NOT NULL,
	"Hora" INTEGER NOT NULL,
	"Dia" INTEGER NOT NULL,
	"Semana" INTEGER NOT NULL,
	"Mes" INTEGER NOT NULL,
	"Ano" INTEGER NOT NULL,
	PRIMARY KEY("SK Tempo"),
	FOREIGN KEY ("SK Tempo") REFERENCES "FATO_OBITO"("SK DT Obito")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_PESSOA" (
	"SK Pessoa" INTEGER,
	"CD Pessoa" INTEGER NOT NULL UNIQUE,
	"DS Idade" INTEGER,
	"DS Sexo" VARCHAR NOT NULL,
	"DS Raca" VARCHAR,
	"DS Estado Civil" VARCHAR,
	"DS Escolaridade" VARCHAR,
	"DS Ocupação" VARCHAR,
	"DS Naturalidade" VARCHAR,
	"DT Nascimento" DATE,
	"DS Municipio Residencia" VARCHAR,
	PRIMARY KEY("SK Pessoa"),
	FOREIGN KEY ("SK Pessoa") REFERENCES "FATO_OBITO"("SK Pessoa")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "FATO_OBITO" (
	"SK Obito" INTEGER NOT NULL,
	"SK Pessoa" INTEGER NOT NULL,
	"SK DT Obito" INTEGER NOT NULL,
	"SK Local Ocorrencia" INTEGER NOT NULL,
	"SK Escolaridade Mae" INTEGER NOT NULL,
	"SK Obito Puerperio" INTEGER NOT NULL,
	"SK Morte Ocorreu" INTEGER NOT NULL,
	"SK Metodo Parto" INTEGER NOT NULL,
	"SK Gestacao Multipla" INTEGER NOT NULL,
	"SK Causa CID" INTEGER NOT NULL,
	"CD Obito" INTEGER NOT NULL UNIQUE,
	"ST Obito Fetal" VARCHAR NOT NULL,
	"DS Municipio Ocorrencia" VARCHAR NOT NULL,
	"DS Idade Mae" INTEGER,
	"DS Ocupacao Mae" VARCHAR,
	"DS Filhos Vivos" INTEGER,
	"DS Filhos Perdas" INTEGER,
	"DS Semanas Gestacao" INTEGER,
	"DS Obito Parto" VARCHAR,
	"DS Peso Nascimento" INTEGER,
	"DS Assistencia Medica" VARCHAR,
	"DS Necropsia" VARCHAR,
	"DS Causa Basica" VARCHAR,
	"DS Local Ocorrencia Acidente" VARCHAR,
	"DS Exame" VARCHAR,
	"DS Cirurgia" VARCHAR,
	PRIMARY KEY("SK Obito")
);
