CREATE TABLE IF NOT EXISTS "DWCD_OBITO_PARTO" (
	"SK Obito Parto" INTEGER NOT NULL,
	"CD Obito Parto" VARCHAR NOT NULL UNIQUE,
	"DS Obito Parto" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Obito Parto"),
	FOREIGN KEY ("SK Obito Parto") REFERENCES "DWMV_OBITO"("DS Obito Parto")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_CAUSA_CID" (
	"SK Causa" INTEGER NOT NULL,
	"CD Causa" VARCHAR NOT NULL UNIQUE,
	"DS Causa" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Causa"),
	FOREIGN KEY ("SK Causa") REFERENCES "DWMV_OBITO"("DS Causa CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_PESSOA" (
	"SK Pessoa" INTEGER NOT NULL,
	"CD Pessoa" INTEGER NOT NULL UNIQUE,
	"DS Idade" INTEGER,
	"CD Sexo" INTEGER NOT NULL,
	"CD Raca" INTEGER,
	"CD Estado Civil" INTEGER,
	"CD Escolaridade" INTEGER,
	"CD Ocupação" INTEGER,
	"CD Naturalidade" INTEGER,
	"DT Nascimento" DATE,
	"CD Municipio Residencia" INTEGER,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Pessoa")
);

CREATE TABLE IF NOT EXISTS "DWMV_OBITO" (
	"SK Obito" INTEGER NOT NULL,
	"CD Obito" INTEGER NOT NULL UNIQUE,
	"ST Obito Fetal" INTEGER NOT NULL,
	"DT Data" DATE NOT NULL,
	"DT Hora" DATETIME,
	"CD Local Ocorrencia" INTEGER NOT NULL,
	"CD Municipio" INTEGER,
	"DS Estabelecimento" INTEGER,
	"DS Idade Mae" INTEGER,
	"CD Escolaridade Mae" INTEGER,
	"DS Ocupacao Mae" INTEGER,
	"DS Filhos Vivos" INTEGER,
	"DS Filhos Perdidos" INTEGER,
	"DS Semanas Gestacao" INTEGER,
	"CD Gestacao Multipla" INTEGER,
	"CD Metodo Parto" INTEGER,
	"DS Obito Parto" INTEGER,
	"DS Peso Nascimento" INTEGER,
	"CD Morte Ocorreu" INTEGER,
	"DS Assistencia Medica" INTEGER,
	"DS Necropsia" INTEGER,
	"DS Causa CID" INTEGER NOT NULL,
	"DS Causa Basica" INTEGER,
	"DS Atestado Medico" INTEGER,
	"DS Municipio SVO IML" INTEGER,
	"DT Atestado" DATE,
	"CD Circunstancia Obito" INTEGER,
	"DS Acidente Trabalho" INTEGER,
	"CD Fonte Informacao" INTEGER,
	"CD Local Tipo Ocorrencia Acidente" INTEGER,
	"CD Obito Puerperio" INTEGER,
	"DS Exame" INTEGER,
	"DS Cirurgia" INTEGER,
	"DT Carga" DATETIME NOT NULL,
	PRIMARY KEY("SK Obito")
);

CREATE TABLE IF NOT EXISTS "DWCD_GESTACAO_MULTIPLA" (
	"SK Gestacao Multipla" INTEGER NOT NULL,
	"CD Gestacao Multipla" INTEGER NOT NULL UNIQUE,
	"DS Gestacao Multipla" VARCHAR NOT NULL UNIQUE,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Gestacao Multipla"),
	FOREIGN KEY ("CD Gestacao Multipla") REFERENCES "DWMV_OBITO"("CD Gestacao Multipla")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPIO" (
	"SK Municipio" INTEGER NOT NULL,
	"CD Municipio" INTEGER NOT NULL UNIQUE,
	"NM Municipio" VARCHAR NOT NULL,
	"CD UF" INTEGER NOT NULL,
	"NM UF" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Municipio"),
	FOREIGN KEY ("CD Municipio") REFERENCES "DWCD_PESSOA"("CD Naturalidade")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD Municipio") REFERENCES "DWMV_OBITO"("CD Municipio")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD Municipio") REFERENCES "DWCD_PESSOA"("CD Municipio Residencia")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESTADO_CIVIL" (
	"SK Estado Civil" INTEGER NOT NULL,
	"CD Estado Civil" INTEGER NOT NULL UNIQUE,
	"DS Estado Civil" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Estado Civil"),
	FOREIGN KEY ("CD Estado Civil") REFERENCES "DWCD_PESSOA"("CD Estado Civil")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_LOCAL_OCORRENCIA" (
	"SK Local Ocorrencia" INTEGER NOT NULL,
	"CD Local Ocorrencia" INTEGER NOT NULL UNIQUE,
	"DS Local Ocorrencia" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Local Ocorrencia"),
	FOREIGN KEY ("CD Local Ocorrencia") REFERENCES "DWMV_OBITO"("CD Local Ocorrencia")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESCOLARIDADE" (
	"SK Escolaridade" INTEGER NOT NULL,
	"CD Escolaridade" INTEGER NOT NULL UNIQUE,
	"DS Escolaridade" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Escolaridade"),
	FOREIGN KEY ("CD Escolaridade") REFERENCES "DWMV_OBITO"("CD Escolaridade Mae")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD Escolaridade") REFERENCES "DWCD_PESSOA"("CD Escolaridade")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_METODO_PARTO" (
	"SK Metodo Parto" INTEGER NOT NULL,
	"CD Metodo Parto" INTEGER NOT NULL UNIQUE,
	"DS Metodo Parto" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Metodo Parto"),
	FOREIGN KEY ("CD Metodo Parto") REFERENCES "DWMV_OBITO"("CD Metodo Parto")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_MORTE_OCORREU" (
	"SK Morte Ocorreu" INTEGER NOT NULL,
	"CD Morte Ocorreu" INTEGER NOT NULL UNIQUE,
	"DS Morte Ocorreu" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Morte Ocorreu"),
	FOREIGN KEY ("CD Morte Ocorreu") REFERENCES "DWMV_OBITO"("CD Morte Ocorreu")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_CIRCUSTANCIA_MORTE" (
	"SK Circunstancia Morte" INTEGER NOT NULL,
	"CD  Circunstancia Morte" INTEGER NOT NULL UNIQUE,
	"DS  Circunstancia Morte" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Circunstancia Morte"),
	FOREIGN KEY ("CD  Circunstancia Morte") REFERENCES "DWMV_OBITO"("CD Circunstancia Obito")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_FONTE_INFORMACAO" (
	"SK Fonte " INTEGER NOT NULL,
	"CD Fonte " INTEGER NOT NULL UNIQUE,
	"DS Fonte Informacao" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Fonte "),
	FOREIGN KEY ("CD Fonte ") REFERENCES "DWMV_OBITO"("CD Fonte Informacao")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_LOCAL_TIPO_OCORRENCIA" (
	"SK Local Tipo Ocorrencia" INTEGER NOT NULL,
	"CD Local Tipo Ocorrencia" INTEGER NOT NULL UNIQUE,
	"DS Local Tipo Ocorrencia" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Local Tipo Ocorrencia"),
	FOREIGN KEY ("CD Local Tipo Ocorrencia") REFERENCES "DWMV_OBITO"("CD Local Tipo Ocorrencia Acidente")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_OBITO_PUERPERIO" (
	"SK Obito Puerperio" INTEGER NOT NULL,
	"CD Obito Puerperio" INTEGER NOT NULL UNIQUE,
	"DS Obito Puerperio" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Obito Puerperio"),
	FOREIGN KEY ("CD Obito Puerperio") REFERENCES "DWMV_OBITO"("CD Obito Puerperio")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_RACA" (
	"SK Raca" INTEGER NOT NULL,
	"CD Raca" INTEGER NOT NULL UNIQUE,
	"DS Raca" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Raca"),
	FOREIGN KEY ("CD Raca") REFERENCES "DWCD_PESSOA"("CD Raca")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
	"SK Sexo" INTEGER NOT NULL,
	"CD Sexo" VARCHAR NOT NULL UNIQUE,
	"DS Sexo" VARCHAR NOT NULL,
	"DT Carga" DATE NOT NULL,
	PRIMARY KEY("SK Sexo"),
	FOREIGN KEY ("CD Sexo") REFERENCES "DWCD_PESSOA"("CD Sexo")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
