CREATE TABLE IF NOT EXISTS "DIME_LOCAL" (
	"SK_Local" INTEGER NOT NULL,
	"CD_UF" INTEGER NOT NULL,
	"NM_UF" VARCHAR NOT NULL,
	"CD_Municipio" INTEGER NOT NULL UNIQUE,
	"NM_Municipio" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Local")
);

CREATE TABLE IF NOT EXISTS "DIME_FAIXA_ETARIA" (
	"SK_Faixa_Etaria" INTEGER NOT NULL,
	"CD_Faixa_Etaria" INTEGER NOT NULL UNIQUE,
	"DS_Faixa_Etaria" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Faixa_Etaria")
);

CREATE TABLE IF NOT EXISTS "DIME_ESTADO_CIVIL" (
	"SK_Estado_Civil" INTEGER NOT NULL,
	"CD_Estado_Civil" INTEGER NOT NULL UNIQUE,
	"DS_Estado_Civil" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Estado_Civil")
);

CREATE TABLE IF NOT EXISTS "DIME_SEXO" (
	"SK_Sexo" INTEGER NOT NULL,
	"CD_Sexo" VARCHAR NOT NULL UNIQUE,
	"DS_Sexo" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Sexo")
);

CREATE TABLE IF NOT EXISTS "DIME_RACA" (
	"SK_Raca" INTEGER NOT NULL,
	"CD_Raca" INTEGER NOT NULL UNIQUE,
	"DS_Raca" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Raca")
);

CREATE TABLE IF NOT EXISTS "DIME_OCUPACAO" (
	"SK_Ocupacao" INTEGER NOT NULL,
	"CD_Ocupacao" INTEGER NOT NULL UNIQUE,
	"DS_Ocupacao" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Ocupacao"),
	FOREIGN KEY ("SK_Ocupacao") REFERENCES "FATO_OBITO"("SK_Ocupacao")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_CID" (
	"SK_CID" INTEGER NOT NULL,
	"CD_CID" VARCHAR NOT NULL UNIQUE,
	"DS_CID" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_CID"),
	FOREIGN KEY ("SK_CID") REFERENCES "FATO_OBITO"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DIME_ESCOLARIDADE" (
	"SK_Escolaridade" INTEGER NOT NULL,
	"CD_Escolaridade" INTEGER NOT NULL UNIQUE,
	"DS_Escolaridade" VARCHAR NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Escolaridade")
);

CREATE TABLE IF NOT EXISTS "DIME_TEMPO" (
	"SK_Tempo" INTEGER NOT NULL UNIQUE,
	"NR_Mes" INTEGER NOT NULL,
	"NR_Ano" INTEGER NOT NULL,
	"DT_Data" DATE NOT NULL,
	PRIMARY KEY("SK_Tempo")
);

CREATE TABLE IF NOT EXISTS "FATO_OBITO" (
	"SK_Raca" INTEGER NOT NULL,
	"SK_Sexo" INTEGER NOT NULL,
	"SK_CID" INTEGER NOT NULL,
	"SK_DT_Obito" INTEGER NOT NULL,
	"SK_Escolaridade" INTEGER NOT NULL,
	"SK_Faixa_Etaria" INTEGER NOT NULL,
	"SK_Estado_Civil" INTEGER NOT NULL,
	"SK_Ocupacao" INTEGER NOT NULL,
	"SK_Local_Obito" INTEGER NOT NULL,
	"NR_Assistencia_Medica" INTEGER NOT NULL,
	"NR_Exame" INTEGER NOT NULL,
	"NR_Cirurgia" INTEGER NOT NULL,
	"NR_Quantidade" INTEGER NOT NULL,
	"DT_Carga" TIMESTAMP NOT NULL,
	PRIMARY KEY("SK_Raca", "SK_Sexo", "SK_CID", "SK_DT_Obito", "SK_Escolaridade", "SK_Faixa_Etaria", "SK_Estado_Civil", "SK_Ocupacao", "SK_Local_Obito"),
	FOREIGN KEY ("SK_DT_Obito") REFERENCES "DIME_TEMPO"("SK_Tempo")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Raca") REFERENCES "DIME_RACA"("SK_Raca")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Sexo") REFERENCES "DIME_SEXO"("SK_Sexo")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Estado_Civil") REFERENCES "DIME_ESTADO_CIVIL"("SK_Estado_Civil")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Faixa_Etaria") REFERENCES "DIME_FAIXA_ETARIA"("SK_Faixa_Etaria")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Local_Obito") REFERENCES "DIME_LOCAL"("SK_Local")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_Escolaridade") REFERENCES "DIME_ESCOLARIDADE"("SK_Escolaridade")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
